language: ruby
rvm:
 - 2.3.1
# uncomment and edit the following line if your project needs to run something other than `rake`:
script: bundle exec rspec
notifications:
  email:
    - cowdrey31088@gmail.com
    - whybothershaving@gmail.com@gmail.com
