language: ruby
rvm:
 - 2.2.2
 - jruby
 - rbx-2
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
notifications:
  email:
    - cowdrey31088@gmail.com
    - whybothershaving@gmail.com@gmail.com
